version: '3.8'

services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile.fastapi
    ports:
      - "8002:8002"

  
  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    ports:
      - "8502:8502"
    depends_on:
    - fastapi