FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["streamlit", "run", "app/streamlit-ui/ui.py", "--server.port=8502", "--server.address=0.0.0.0"]